---
version: "2.1"
services:
  app:
    image: homestats
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./settings.json:/app/settings.json
    depends_on:
      - influxdb
    links:
      - "influxdb:db"
  influxdb:
    image: influxdb
    container_name: influxdb
    environment:
      - INFLUXDB_USER=monitoring
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=password
      - INFLUXDB_HTTP_AUTH_ENABLED=true
    volumes:
      - influxdb-volume:/var/lib/influxdb
      # Initialization script to create homestats database
      - ./scripts:/docker-entrypoint-initdb.d
    ports:
      - 8086:8086
    restart: unless-stopped
  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - grafana-volume:/var/lib/grafana
    ports:
      - 3000:3000
    links:
      - influxdb
    user: "472"
    depends_on:
      - influxdb
    restart: unless-stopped

volumes:
  influxdb-volume:
  grafana-volume:
