---
version: "2.1"
services:
  influxdb:
    image: influxdb
    container_name: influxdb
    environment:
      - INFLUXDB_USER=monitoring
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=password
    volumes:
      - influxdb-volume:/var/lib/influxdb
    ports:
      - 8086:8086
    restart: unless-stopped
  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - grafana-volume:/var/lib/grafana
    ports:
      - 3000:3000
    links:
      - influxdb
    user: "472"
    restart: unless-stopped

volumes:
  influxdb-volume:
  grafana-volume:
